# FROM golang:1.20-alpine

# # Install Go
# # RUN apt-get update && apt-get install -y wget \
# #     && wget https://go.dev/dl/go1.21.8.linux-amd64.tar.gz \
# #     && tar -C /usr/local -xzf go1.21.8.linux-amd64.tar.gz \
# #     && rm go1.21.8.linux-amd64.tar.gz
    

# # Set Go environment variables
# # ENV PATH=$PATH:/usr/local/go/bin
# # ENV PATH=$PATH:/go/bin
# # ENV GOPATH=/go

# # Set the working directory for the application
# WORKDIR /app

# # Copy the package.json and package-lock.json (if available)
# COPY . .

# # Install wails
# CMD go run ./api.go

# # Expose a port (if needed)
# EXPOSE 80