// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDID():Promise<string>;

export function GetListOfDIDs():Promise<Array<string>>;

export function GetListOfVCs(arg1:string):Promise<Array<string>>;

export function GetVCsOfDIDs(arg1:string):Promise<string>;
