// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDID() {
  return window['go']['main']['App']['AddDID']();
}

export function GetListOfDIDs() {
  return window['go']['main']['App']['GetListOfDIDs']();
}

export function GetListOfVCs(arg1) {
  return window['go']['main']['App']['GetListOfVCs'](arg1);
}

export function GetVCsOfDIDs(arg1) {
  return window['go']['main']['App']['GetVCsOfDIDs'](arg1);
}
