// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wallet} from '../models';

export function GetListOfDIDs():Promise<Array<wallet.DID>>;

export function GetListOfVCs(arg1:string):Promise<Array<string>>;
