// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetListOfDIDs() {
  return window['go']['main']['App']['GetListOfDIDs']();
}

export function GetListOfVCs(arg1) {
  return window['go']['main']['App']['GetListOfVCs'](arg1);
}

export function RefreshVCs() {
  return window['go']['main']['App']['RefreshVCs']();
}

export function StoreVC(arg1, arg2) {
  return window['go']['main']['App']['StoreVC'](arg1, arg2);
}
